main: main.o fonctions_exo3.o
	gcc -Wall -o main.exe main.o fonctions_exo33.o

main.o: main.c fonctions3.h
	gcc -Wall -c main.c

fonctions_exo3.o: fonctions_exo3.c fonctions3.h
	gcc -Wall -c fonctions_exo33.c
